export default [
  {
    slug: 'usd',
    flag: '🇺🇸',
    name: 'USD',
    symbol: '$',
    fullName: 'United States Dollar',
  },
  {
    flag: '🇪🇺',
    slug: 'eur',
    name: 'EUR',
    symbol: '€',
    fullName: 'Euro',
  },
  {
    flag: '🇬🇧',
    slug: 'gbp',
    name: 'GBP',
    symbol: '£',
    fullName: 'British Pound Sterling',
  },
  {
    flag: '🇯🇵',
    slug: 'jpy',
    name: 'JPY',
    symbol: '¥',
    fullName: 'Japanese Yen',
  },
  {
    flag: '🇨🇳',
    slug: 'cny',
    name: 'CNY',
    symbol: '¥',
    fullName: 'Chinese Yuan',
  },
  {
    flag: '🇨🇦',
    slug: 'cad',
    name: 'CAD',
    symbol: '$',
    fullName: 'Canadian Dollar',
  },
  {
    flag: '🇦🇺',
    slug: 'aud',
    name: 'AUD',
    symbol: '$',
    fullName: 'Australian Dollar',
  },
  {
    flag: '🇳🇿',
    slug: 'chf',
    name: 'CHF',
    symbol: '₣',
    fullName: 'Swiss Franc',
  },
];
